#!/bin/bash

set -euo pipefail

echo '--- Setting clone flags'

echo "current settings:
BUILDKITE_GIT_MIRRORS_PATH=${BUILDKITE_GIT_MIRRORS_PATH:-}
BUILDKITE_GIT_CLONE_MIRROR_FLAGS=${BUILDKITE_GIT_CLONE_MIRROR_FLAGS:-}

BUILDKITE_GIT_CLONE_FLAGS=${BUILDKITE_GIT_CLONE_FLAGS:-}
BUILDKITE_GIT_FETCH_FLAGS=${BUILDKITE_GIT_FETCH_FLAGS:-}
"




# echo "blobby"
# export BUILDKITE_GIT_CLONE_MIRROR_FLAGS="-v --mirror --filter=blob:none"

echo "disable mirrors for this build"
unset BUILDKITE_GIT_MIRRORS_PATH
export BUILDKITE_GIT_CLONE_MIRROR_FLAGS="-v --filter=blob:none"
export BUILDKITE_GIT_CLONE_FLAGS="-v --dissociate --filter=blob:none"

# defaults
# BUILDKITE_GIT_CLONE_MIRROR_FLAGS=-v
# BUILDKITE_GIT_CLONE_FLAGS=-v --dissociate
# BUILDKITE_GIT_FETCH_FLAGS=-v --prune

sanitise_github_url() {
    local url="$1"
    local sanitized="${url//[^a-zA-Z0-9]/-}"
    echo "$sanitized"
}

echo "Starting timer for experimental checkout"
timestamp=$(date +%s)
export CHECKOUT_START_TIME="$timestamp"
